dictionaries = ["en_us"]

words = [
  "pyproject",
  "pytest",
  "aacebedo",
  "actionid",
  "addgroup",
  "adduser",
  "apparmor",
  "aquasecurity",
  "autodiscover",
  "autodiscovered",
  "autodiscovery",
  "autoqueue",
  "biome's",
  "biomejs",
  "blopker",
  "captureindex",
  "cargopackage",
  "cgroupns",
  "chmod",
  "cjs",
  "cli",
  "clippy",
  "cocogitto",
  "codebook",
  "commitizen",
  "commitusingapi",
  "copier",
  "cpython",
  "cron",
  "devcontainer",
  "devcontaineruser",
  "djlint",
  "dockerfile's",
  "dockerfmt",
  "dockerimage",
  "dotfiles",
  "doublestar",
  "editorconfig",
  "envops",
  "eof",
  "findsubmatch",
  "frontmatter",
  "githubrelease",
  "gohugoio",
  "goldmark",
  "groupby",
  "hadolint",
  "inlines",
  "jdx",
  "koalaman",
  "libmagic",
  "linters",
  "matchpattern",
  "mergify",
  "mise",
  "mise's",
  "mkdir",
  "mvdan",
  "opencontainers",
  "owenlamont",
  "pep440",
  "pipefail",
  "pipx",
  "podman",
  "prek",
  "programdata",
  "pullrequest",
  "pycache",
  "pypi",
  "rel's",
  "replacepattern",
  "repo's",
  "reteps",
  "rumdl",
  "rustfmt",
  "rvben",
  "ryl",
  "scmid",
  "scms",
  "scop",
  "sed",
  "shellcheck",
  "shfmt",
  "sourceid",
  "systemdrive",
  "tagfilter",
  "tombi",
  "toml's",
  "trimprefix",
  "trivy",
  "trivyignore",
  "ulimit",
  "unreviewed",
  "updatecli",
  "userprofile",
  "venv",
  "versionfilter",
  "xdg",
  "yamlfmt",
  "yamllint",
  "yamllint's",
]

ignore_paths = [
  ".copier-answers*.yml",
  "CHANGELOG.md",
  "cog.toml",
  ".git/**",
  "REUSE.toml",
]
