dictionaries = ["en_us"]

words = [
  "aacebedo",
  "actionid",
  "aquasecurity",
  "autodiscover",
  "autodiscovered",
  "autodiscovery",
  "autoqueue",
  "biomejs",
  "blopker",
  "captureindex",
  "cjs",
  "cli",
  "cocogitto",
  "codebook",
  "commitizen",
  "commitusingapi",
  "copier",
  "cron",
  "devcontainer",
  "devcontaineruser",
  "dotfiles",
  "doublestar",
  "editorconfig",
  "findsubmatch",
  "githubrelease",
  "groupby",
  "jdx",
  "koalaman",
  "linters",
  "matchpattern",
  "mergify",
  "mise",
  "mise's",
  "mkdir",
  "mvdan",
  "owenlamont",
  "pep440",
  "pipefail",
  "prek",
  "pullrequest",
  "pypi",
  "replacepattern",
  "rumdl",
  "rvben",
  "ryl",
  "scmid",
  "scms",
  "scop",
  "sed",
  "shellcheck",
  "shfmt",
  "sourceid",
  "tombi",
  "trimprefix",
  "trivy",
  "updatecli",
  "venv",
  "versionfilter",
  "yamlfmt",
  "yamllint",
  "yamllint's",
]

ignore_paths = [
  ".copier-answers*.yml",
  "CHANGELOG.md",
  "cog.toml",
  ".git/**",
  "REUSE.toml",
]
