---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
permissions: {}
jobs:
  release:
    runs-on: ubuntu-26.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          fetch-tags: true
      - name: Setup
        uses: ./.github/actions/setup
      - name: Configure git remote and user info
        shell: bash
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin \
            "https://${REPO_OWNER}:${TOKEN}@github.com/${REPO}.git"
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
      - name: Perform release
        run: mise run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
